name: Build Test
on:
  pull_request:

env:
  DOCKER_USERNAME: tiryoh
  DOCKER_IMAGENAME: jekyll

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jekyll-version:
          - '3.8.7'
          - '3.9.3'
          - '4.0.1'
          - '4.1.1'
          - '4.2.2'
          - '4.3.2'
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-22.04
          - arch: arm64
            runner: ubuntu-22.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGENAME }}
          tags: |
            type=raw,value=${{ matrix.jekyll-version }}-{{date 'YYYYMMDDTHHmm'}}
            type=raw,value=${{ matrix.jekyll-version }}
          flavor: |
            latest=${{ matrix.jekyll-version == '4.2.1' }}
            prefix=
            suffix=

      - name: Parse docker build option
        id: docker-build-option
        shell: bash
        run: |
          LABELS=$(cat << EOF | grep -E "=." | sed -e "s/org\./--label org./g" | sed -e "s/--label org\(.*\)=\(.*\)$/--label org\1='\2'/g"
          ${{ steps.meta.outputs.labels }}
          EOF
          )
          echo $LABELS
          echo "labels=${LABELS}" >> $GITHUB_OUTPUT

      - name: Build docker image
        env:
          DOCKER_TAGNAME: ${{ matrix.jekyll-version }}
        shell: bash
        run: |
          docker buildx build  --no-cache --platform=linux/${{ matrix.arch }} \
          --progress=plain ${{ steps.docker-build-option.outputs.labels }} \
          --build-arg JEKYLL_VERSION=${{ matrix.jekyll-version }} \
          --build-arg JEKYLL_DOCKER_TAG=${{ matrix.jekyll-version }} \
          --build-arg RUBYOPT='-W0' \
          --build-arg JEKYLL_DOCKER_COMMIT=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }} \
          --build-arg JEKYLL_DOCKER_NAME=${{ env.DOCKER_IMAGENAME }} \
          -t ${{ env.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGENAME }}:$DOCKER_TAGNAME .
